// Generated by scripts/sync-browser-providers.mjs; edit the provider source repositories.
import { createBrowserProviderRegistry } from './contract.js';
import provider0 from './packages/civitai/index.js';
import provider1 from './packages/deviantart/index.js';
import provider2 from './packages/wallhaven/index.js';
export const browserProviders = createBrowserProviderRegistry([provider0, provider1, provider2]);
